# lightning.pytorch==2.1.2
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: ./logs
        name: simple_remote_train
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: null
        filename: 'epoch_{epoch}_step_{step}_val_loss_{val_loss:.2f}'
        save_top_k: 3
        monitor: 'val_loss'
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: ./logs
model:
  batch_size: 32
  num_points: 1000
  n_prediction_per_point: 20
  dbscan_eps: 0.2
  dbscan_min_samples: 500
  n_jobs: 4
data:
  train_data_path: /data/shrec_2023/benchmark-train
  test_data_path: /data/shrec_2023/benchmark-test
  predict_data_path: /data/shrec_2023/benchmark-test
  does_predict_has_ground_truths: true
  batch_size: 2
  transform: null
  collate_function: src.dataset.shrec2023.default_symmetry_dataset_collate_fn
  validation_percentage: 0.1
  shuffle: true
  n_workers: 4
ckpt_path: null
